from __future__ import annotations

from dataclasses import dataclass
from typing import BinaryIO, Protocol


@dataclass(frozen=True)
class Entry:
    name: str
    type: str
    size: int | None
    mtime: str | None
    perms: str | None = None


@dataclass(frozen=True)
class FileInfo:
    path: str
    type: str
    size: int | None
    mtime: str | None
    perms: str | None = None


class Driver(Protocol):
    def banner(self) -> str: ...
    def list_dir(self, path: str) -> list[Entry]: ...
    def get_info(self, path: str) -> FileInfo: ...
    def download(self, path: str, target: BinaryIO) -> FileInfo: ...
    def upload(self, source: BinaryIO, path: str, overwrite: bool) -> int: ...
    def supports_atomic_replace(self) -> bool: ...
    def commit_upload(self, temporary_path: str, final_path: str, *, overwrite: bool) -> None: ...
    def check_path(self, path: str, root: str, *, allow_missing_final: bool = False) -> None: ...
    def exists(self, path: str) -> bool: ...
    def make_dir(self, path: str) -> list[str]: ...
    def read_prefix(self, path: str, max_bytes: int) -> bytes: ...
    def walk(self, path: str) -> list[FileInfo]: ...
    def move(self, from_path: str, to_path: str) -> None: ...
    def delete_file(self, path: str) -> None: ...
    def delete_dir(self, path: str) -> None: ...
    def close(self) -> None: ...
